### PR TITLE
  refs #2977 NEW MH-12930: Fill creator metadata field with actual us…

### PR DESCRIPTION
**Pull request by jchssystems**
Fill the creator metadata field with the actual user, the one who is logged in. The creator metadata has already the logged user, so the field in the wizards _Create event_ and _Event details_  is only an UI field. No configurations required. The field is created and filled by code.

### CODE REVIEW

**Comment by hsssystems** [comment]
Patch ist super! Der Text ist kein gutes Englisch, versteht man nicht. Also ich versteh es auch nicht.  Schreib doch mal auf spanisch und benutze den Uebersetzer hier : https://www.deepl.com/translator

Mach ich mal mit diesem Text:

¡Patch es genial! El texto no es un buen inglés, no lo entiendes. Bueno, yo tampoco lo entiendo.  Escriba en español y utilice el traductor aquí: https://www.deepl.com/translator

**Comment by jchssystems** [comment]
The createdby field will have the user who created the event. The metadata creator already contains this information, so the new field is a field for the graphical interface. No configuration is required. 

The field will be filled with the user logged in in the new event wizard and with the value of the creator metadata in the event details wizard.

**Comment by hsssystems** [comment]
Added new _createdby_ field to adminui. The metadata field _creator_ exists already, so no additional configuration is required.

The field may hold the logged in user in in the new event wizard.

**Comment by jchssystems** [comment]
Added new _createdby_ field to the adminui. The metadata field creator exists already, so no additional configuration is required. See similar implementation for series.

The field may hold the logged in user in in the new event wizard. We will provide this patch in a seperate pr.

**Comment by hsssystems** [comment]
Added a new _createdby_ field to the adminui. The metadata field _creator_ exists already, so no additional configuration is required. See similar implementation for series.

The field holds the logged in user in in the new event wizard.

**Pull request closed without merging**
